# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_pin.xdc

# IP: ip/ila_0/ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: ip/clk_125_gen/clk_125_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_125_gen || ORIG_REF_NAME==clk_125_gen} -quiet] -quiet

# XDC: ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ila_0/ila_0_ooc.xdc

# XDC: ip/clk_125_gen/clk_125_gen_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_125_gen || ORIG_REF_NAME==clk_125_gen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_125_gen/clk_125_gen.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_125_gen || ORIG_REF_NAME==clk_125_gen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_125_gen/clk_125_gen_ooc.xdc
