######################################################################
#
# File name : tb_top_ddr3_hdmi_wave.do
# Created on: Fri Nov 01 20:16:07 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
