# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_pin.xdc

# IP: ip/ila_32bit/ila_32bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_32bit || ORIG_REF_NAME==ila_32bit} -quiet] -quiet

# IP: ip/pll_rx_clk_90/pll_rx_clk_90.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pll_rx_clk_90 || ORIG_REF_NAME==pll_rx_clk_90} -quiet] -quiet

# XDC: ip/ila_32bit/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_32bit || ORIG_REF_NAME==ila_32bit} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ila_32bit/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_32bit || ORIG_REF_NAME==ila_32bit} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ila_32bit/ila_32bit_ooc.xdc

# XDC: ip/pll_rx_clk_90/pll_rx_clk_90_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll_rx_clk_90 || ORIG_REF_NAME==pll_rx_clk_90} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/pll_rx_clk_90/pll_rx_clk_90.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll_rx_clk_90 || ORIG_REF_NAME==pll_rx_clk_90} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/pll_rx_clk_90/pll_rx_clk_90_ooc.xdc
