set_property IOSTANDARD LVCMOS33 [get_ports sclkin]
set_property IOSTANDARD LVCMOS33 [get_ports srst_n]
set_property PACKAGE_PIN W19 [get_ports sclkin]
set_property PACKAGE_PIN Y18 [get_ports srst_n]


set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_d0_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_d0_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_d1_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_d1_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_d2_p]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_d2_n]
set_property PACKAGE_PIN C18 [get_ports hdmi_clk_p]
set_property PACKAGE_PIN D20 [get_ports hdmi_d0_p]
set_property PACKAGE_PIN C22 [get_ports hdmi_d1_p]
set_property PACKAGE_PIN B21 [get_ports hdmi_d2_p]