######################################################################
#
# File name : tb_top_ddr3_hdmi_wave.do
# Created on: Wed Oct 30 17:28:34 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
