######################################################################
#
# File name : tb_gige.udo
# Created on: Mon Feb 10 21:11:29 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
