######################################################################
#
# File name : tb_ddr3_hdmi_wave.do
# Created on: Thu Oct 31 10:24:58 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
