######################################################################
#
# File name : tb_top_ddr3_hdmi_wave.do
# Created on: Thu Oct 31 17:05:36 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
