######################################################################
#
# File name : tb_ddr3_hdmi_wave.do
# Created on: Tue Oct 29 16:50:28 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
