######################################################################
#
# File name : tb_top_ddr3_hdmi_wave.do
# Created on: Tue Oct 29 15:00:21 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
