# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/toppin.xdc

# IP: ip/ila_0/ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: ip/blk_wr8x4096/blk_wr8x4096.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_wr8x4096 || ORIG_REF_NAME==blk_wr8x4096} -quiet] -quiet

# IP: ip/ddr3_ctrl/ddr3_ctrl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr3_ctrl || ORIG_REF_NAME==ddr3_ctrl} -quiet] -quiet

# IP: ip/wr_data_fifo_ctrl/wr_data_fifo_ctrl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wr_data_fifo_ctrl || ORIG_REF_NAME==wr_data_fifo_ctrl} -quiet] -quiet

# IP: ip/wr_cmd_fifo_ctrl/wr_cmd_fifo_ctrl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wr_cmd_fifo_ctrl || ORIG_REF_NAME==wr_cmd_fifo_ctrl} -quiet] -quiet

# IP: ip/rd_cmd_fifo_ctrl/rd_cmd_fifo_ctrl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rd_cmd_fifo_ctrl || ORIG_REF_NAME==rd_cmd_fifo_ctrl} -quiet] -quiet

# IP: ip/rd_data_fifo_ctrl/rd_data_fifo_ctrl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rd_data_fifo_ctrl || ORIG_REF_NAME==rd_data_fifo_ctrl} -quiet] -quiet

# IP: ip/asfifo_wr128x512_rd16x4096/asfifo_wr128x512_rd16x4096.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==asfifo_wr128x512_rd16x4096 || ORIG_REF_NAME==asfifo_wr128x512_rd16x4096} -quiet] -quiet

# IP: ip/fifo_wr16x1024_rd128x128/fifo_wr16x1024_rd128x128.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_wr16x1024_rd128x128 || ORIG_REF_NAME==fifo_wr16x1024_rd128x128} -quiet] -quiet

# IP: ip/afifo_wr16x64/afifo_wr16x64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo_wr16x64 || ORIG_REF_NAME==afifo_wr16x64} -quiet] -quiet

# IP: ip/afifo_wr8x8192/afifo_wr8x8192.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo_wr8x8192 || ORIG_REF_NAME==afifo_wr8x8192} -quiet] -quiet

# IP: ip/clk_125_gen/clk_125_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_125_gen || ORIG_REF_NAME==clk_125_gen} -quiet] -quiet

# IP: ip/hdmi_clk_gen/hdmi_clk_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_clk_gen || ORIG_REF_NAME==hdmi_clk_gen} -quiet] -quiet

# IP: ip/ddr3_clk_gen/ddr3_clk_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr3_clk_gen || ORIG_REF_NAME==ddr3_clk_gen} -quiet] -quiet

# XDC: ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ila_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ila_0/ila_0_ooc.xdc

# XDC: ip/blk_wr8x4096/blk_wr8x4096_ooc.xdc

# XDC: ip/ddr3_ctrl/ddr3_ctrl/user_design/constraints/ddr3_ctrl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr3_ctrl || ORIG_REF_NAME==ddr3_ctrl} -quiet] -quiet

# XDC: ip/ddr3_ctrl/ddr3_ctrl/user_design/constraints/ddr3_ctrl_ooc.xdc

# XDC: ip/wr_data_fifo_ctrl/wr_data_fifo_ctrl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==wr_data_fifo_ctrl || ORIG_REF_NAME==wr_data_fifo_ctrl} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/wr_data_fifo_ctrl/wr_data_fifo_ctrl_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==wr_data_fifo_ctrl || ORIG_REF_NAME==wr_data_fifo_ctrl} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/wr_cmd_fifo_ctrl/wr_cmd_fifo_ctrl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==wr_cmd_fifo_ctrl || ORIG_REF_NAME==wr_cmd_fifo_ctrl} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/wr_cmd_fifo_ctrl/wr_cmd_fifo_ctrl_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==wr_cmd_fifo_ctrl || ORIG_REF_NAME==wr_cmd_fifo_ctrl} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/rd_cmd_fifo_ctrl/rd_cmd_fifo_ctrl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rd_cmd_fifo_ctrl || ORIG_REF_NAME==rd_cmd_fifo_ctrl} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/rd_cmd_fifo_ctrl/rd_cmd_fifo_ctrl_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rd_cmd_fifo_ctrl || ORIG_REF_NAME==rd_cmd_fifo_ctrl} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/rd_data_fifo_ctrl/rd_data_fifo_ctrl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rd_data_fifo_ctrl || ORIG_REF_NAME==rd_data_fifo_ctrl} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/rd_data_fifo_ctrl/rd_data_fifo_ctrl_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==rd_data_fifo_ctrl || ORIG_REF_NAME==rd_data_fifo_ctrl} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/asfifo_wr128x512_rd16x4096/asfifo_wr128x512_rd16x4096.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asfifo_wr128x512_rd16x4096 || ORIG_REF_NAME==asfifo_wr128x512_rd16x4096} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/asfifo_wr128x512_rd16x4096/asfifo_wr128x512_rd16x4096_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==asfifo_wr128x512_rd16x4096 || ORIG_REF_NAME==asfifo_wr128x512_rd16x4096} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_wr16x1024_rd128x128/fifo_wr16x1024_rd128x128.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_wr16x1024_rd128x128 || ORIG_REF_NAME==fifo_wr16x1024_rd128x128} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/afifo_wr16x64/afifo_wr16x64.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo_wr16x64 || ORIG_REF_NAME==afifo_wr16x64} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/afifo_wr16x64/afifo_wr16x64_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo_wr16x64 || ORIG_REF_NAME==afifo_wr16x64} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/afifo_wr8x8192/afifo_wr8x8192.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo_wr8x8192 || ORIG_REF_NAME==afifo_wr8x8192} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/afifo_wr8x8192/afifo_wr8x8192_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo_wr8x8192 || ORIG_REF_NAME==afifo_wr8x8192} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/clk_125_gen/clk_125_gen_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_125_gen || ORIG_REF_NAME==clk_125_gen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_125_gen/clk_125_gen.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_125_gen || ORIG_REF_NAME==clk_125_gen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_125_gen/clk_125_gen_ooc.xdc

# XDC: ip/hdmi_clk_gen/hdmi_clk_gen_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_clk_gen || ORIG_REF_NAME==hdmi_clk_gen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/hdmi_clk_gen/hdmi_clk_gen.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_clk_gen || ORIG_REF_NAME==hdmi_clk_gen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/hdmi_clk_gen/hdmi_clk_gen_ooc.xdc

# XDC: ip/ddr3_clk_gen/ddr3_clk_gen_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr3_clk_gen || ORIG_REF_NAME==ddr3_clk_gen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ddr3_clk_gen/ddr3_clk_gen.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr3_clk_gen || ORIG_REF_NAME==ddr3_clk_gen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/ddr3_clk_gen/ddr3_clk_gen_ooc.xdc
