######################################################################
#
# File name : tb_gige_compile.do
# Created on: Wed Feb 12 16:07:34 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\ProgramData\\modeltech64_10.7\\win64\\vlib modelsim_lib/work
D:\\ProgramData\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim

D:\\ProgramData\\modeltech64_10.7\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\ProgramData\\modeltech64_10.7\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\ProgramData\\modeltech64_10.7\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../gige_tx_frame.srcs/sources_1/ip/blk_wr8x4096/sim/blk_wr8x4096.v" \
"../../../../gige_tx_frame.srcs/sources_1/new/checksum_ctrl.v" \
"../../../../gige_tx_frame.srcs/sources_1/new/crc32_d8_send_02.v" \
"../../../../gige_tx_frame.srcs/sources_1/new/gen_frame_ctrl.v" \
"../../../../gige_tx_frame.srcs/sources_1/new/oddr_ctrl.v" \
"../../../../gige_tx_frame.srcs/sources_1/new/timer.v" \
"../../../../gige_tx_frame.srcs/sources_1/new/top_gige.v" \
"../../../../gige_tx_frame.srcs/sim_1/new/tb_gige.v" \


# compile glbl module
D:\\ProgramData\\modeltech64_10.7\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

