######################################################################
#
# File name : tb_gige.udo
# Created on: Wed Feb 12 16:07:37 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
