######################################################################
#
# File name : tb_gige_wave.do
# Created on: Wed Feb 12 16:07:37 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
