# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top_pin.xdc

# IP: ip/bram_wr8x256/bram_wr8x256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_wr8x256 || ORIG_REF_NAME==bram_wr8x256} -quiet] -quiet

# IP: ip/clk_125_gen/clk_125_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_125_gen || ORIG_REF_NAME==clk_125_gen} -quiet] -quiet

# IP: ip/pll_clk_125/pll_clk_125.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pll_clk_125 || ORIG_REF_NAME==pll_clk_125} -quiet] -quiet

# XDC: ip/bram_wr8x256/bram_wr8x256_ooc.xdc

# XDC: ip/clk_125_gen/clk_125_gen_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_125_gen || ORIG_REF_NAME==clk_125_gen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_125_gen/clk_125_gen.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_125_gen || ORIG_REF_NAME==clk_125_gen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_125_gen/clk_125_gen_ooc.xdc

# XDC: ip/pll_clk_125/pll_clk_125_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll_clk_125 || ORIG_REF_NAME==pll_clk_125} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/pll_clk_125/pll_clk_125.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll_clk_125 || ORIG_REF_NAME==pll_clk_125} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/pll_clk_125/pll_clk_125_ooc.xdc
