# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath D:/ProgramData/modeltech64_10.7/win64
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a75tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.cache/wt [current_project]
set_property parent.project_path E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/new/add_check_sum.v
  E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/new/crc32_d8_send_02.v
  E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/new/gen_frame_ctrl.v
  E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/new/oddr_ctrl.v
  E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/new/timer.v
  E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/new/top_gige.v
}
read_ip -quiet E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/ip/bram_wr8x256/bram_wr8x256.xci
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/ip/bram_wr8x256/bram_wr8x256_ooc.xdc]

read_ip -quiet E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/ip/clk_125_gen/clk_125_gen.xci
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/ip/clk_125_gen/clk_125_gen_board.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/ip/clk_125_gen/clk_125_gen.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/ip/clk_125_gen/clk_125_gen_ooc.xdc]

read_ip -quiet E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/ip/pll_clk_125/pll_clk_125.xci
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/ip/pll_clk_125/pll_clk_125_board.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/ip/pll_clk_125/pll_clk_125.xdc]
set_property used_in_implementation false [get_files -all e:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/ip/pll_clk_125/pll_clk_125_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/constrs_1/new/top_pin.xdc
set_property used_in_implementation false [get_files E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/constrs_1/new/top_pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_gige -part xc7a75tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_gige.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_gige_utilization_synth.rpt -pb top_gige_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
