# sys
set_property PACKAGE_PIN Y18 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN W19 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
# phy rgmii tx 
set_property PACKAGE_PIN N18 [get_ports phy_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports tx_clk]
set_property PACKAGE_PIN K18 [get_ports tx_clk]
set_property PACKAGE_PIN M18 [get_ports tx_ctrl]
set_property IOSTANDARD LVCMOS33 [get_ports tx_ctrl]
set_property PACKAGE_PIN M22 [get_ports {tx_dat[0]}]
set_property PACKAGE_PIN L18 [get_ports {tx_dat[1]}]
set_property PACKAGE_PIN L19 [get_ports {tx_dat[2]}]
set_property PACKAGE_PIN L20 [get_ports {tx_dat[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_dat[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_dat[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_dat[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tx_dat[0]}]