set_property SRC_FILE_INFO {cfile:e:/Exercise/FPGA/v3edu/test08_Gige_RGMII/design/Gige_HDMI/Gige_HDMI.srcs/sources_1/ip/pll_rx_clk_90/pll_rx_clk_90.xdc rfile:../../../Gige_HDMI.srcs/sources_1/ip/pll_rx_clk_90/pll_rx_clk_90.xdc id:1 order:EARLY scoped_inst:inst_pll_rx_clk_90/inst} [current_design]
set_property SRC_FILE_INFO {cfile:E:/Exercise/FPGA/v3edu/test08_Gige_RGMII/design/Gige_HDMI/Gige_HDMI.srcs/constrs_1/new/top_pin.xdc rfile:../../../Gige_HDMI.srcs/constrs_1/new/top_pin.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports rx_clk]] 0.08
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports rst_n]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports clk]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J19 [get_ports rx_clk]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports phy_rst_n]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H22 [get_ports rx_ctrl]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K22 [get_ports {rx_dat[0]}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K21 [get_ports {rx_dat[1]}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J22 [get_ports {rx_dat[2]}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J20 [get_ports {rx_dat[3]}]
