######################################################################
#
# File name : tb_top_ddr3_hdmi_wave.do
# Created on: Sat Sep 14 18:07:00 +0800 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
