######################################################################
#
# File name : tb_top_gige.udo
# Created on: Tue Feb 11 14:45:29 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
