set_property SRC_FILE_INFO {cfile:e:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/sources_1/ip/pll_clk_125/pll_clk_125.xdc rfile:../../../gige_tx_frame.srcs/sources_1/ip/pll_clk_125/pll_clk_125.xdc id:1 order:EARLY scoped_inst:inst_pll_clk_125/inst} [current_design]
set_property SRC_FILE_INFO {cfile:E:/Exercise/FPGA/v3edu/test13_tx_crc_oddr/design/gige_tx_frame.srcs/constrs_1/new/top_pin.xdc rfile:../../../gige_tx_frame.srcs/constrs_1/new/top_pin.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.2
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports rst_n]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W19 [get_ports clk]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports phy_rst_n]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports tx_clk]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports tx_ctrl]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22 [get_ports {tx_dat[0]}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L18 [get_ports {tx_dat[1]}]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L19 [get_ports {tx_dat[2]}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L20 [get_ports {tx_dat[3]}]
